---


- name: apache
  when: hr_service_provider == 'apache'
  become: true
  become_user: root
  block:
    - name: http redirect to {{ hr_to_domain }}
      template:
        src: conf.j2
        dest: "{{ hr_httpd_conf_dir }}/{{ hr_configuration_filename }}"
      notify: httpd
      when: not hr_remove

    - name: remove http redirect to {{ hr_to_domain }}
      file:
        path: "{{ hr_httpd_conf_dir }}/{{ hr_configuration_filename }}"
        state: absent
      notify: httpd
      when: hr_remove

- name: apache
  when: hr_service_provider == 'nginx'
  become: true
  become_user: root
  block:
    - name: http redirect to {{ hr_to_domain }}
      template:
        src: nginx.conf.j2
        dest: "{{ hr_nginx_conf_dir }}/{{ hr_configuration_filename }}"
      notify: nginx
      when: not hr_remove

    - name: remove http redirect to {{ hr_to_domain }}
      file:
        path: "{{ hr_nginx_conf_dir }}/{{ hr_configuration_filename }}"
        state: absent
      notify: nginx
      when: hr_remove
